import "./globals.css";
import "@tamagui/core/reset.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./_providers/";
import NextTamaguiSupport from "./_providers/next-tamagui-support";

if (process.env.NODE_ENV === "production") {
  require("../public/tamagui.css");
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NextTamaguiSupport>{children}</NextTamaguiSupport>
        </Providers>
      </body>
    </html>
  );
}
